### ISSUE TITLE
大佬能不能做一个作为插件的Releases？

### ISSUE THREAD

**Issue by rhwong** [hundunzhidian/valvemiraibot#2]
我现在已有基于Mirai-OK的bot，想作为功能添加该怎么做呢？
学生党没有java基础，只能舔舔大佬了

**Comment by hundunzhidian** [comment]
有适配的cqhttp插件https://github.com/yyuueexxiinngg/cqhttp-mirai，再使用针对cqhttp的服务端即可https://github.com/hundunzhidian/qqrobota2srcon
